// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StellarisSaveParser;

namespace StellarisSaveParser.Migrations
{
    [DbContext(typeof(SaveParserContext))]
    partial class SaveParserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StellarisSaveParser.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuildingGameId")
                        .HasColumnType("int");

                    b.Property<int?>("PlanetId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuildingId");

                    b.HasIndex("PlanetId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("StellarisSaveParser.Context.Models.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PlanetId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DistrictId");

                    b.HasIndex("PlanetId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("StellarisSaveParser.Context.Models.Hyperlane", b =>
                {
                    b.Property<int>("hyperlaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GalacticObjectID")
                        .HasColumnType("int");

                    b.Property<int>("distance")
                        .HasColumnType("int");

                    b.Property<int>("targetId")
                        .HasColumnType("int");

                    b.HasKey("hyperlaneId");

                    b.HasIndex("GalacticObjectID");

                    b.ToTable("Hyperlane");
                });

            modelBuilder.Entity("StellarisSaveParser.GalacticObject", b =>
                {
                    b.Property<int>("GalacticObjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GalacticObjectGameId")
                        .HasColumnType("int");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GalacticObjectID");

                    b.ToTable("GalacticObjects");
                });

            modelBuilder.Entity("StellarisSaveParser.Planet", b =>
                {
                    b.Property<int>("PlanetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Controller")
                        .HasColumnType("int");

                    b.Property<float>("Crime")
                        .HasColumnType("real");

                    b.Property<int?>("GalacticObjectID")
                        .HasColumnType("int");

                    b.Property<float>("Migration")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Owner")
                        .HasColumnType("int");

                    b.Property<int>("PlanetGameId")
                        .HasColumnType("int");

                    b.Property<string>("Planet_class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Stability")
                        .HasColumnType("real");

                    b.HasKey("PlanetId");

                    b.HasIndex("GalacticObjectID");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("StellarisSaveParser.Pop", b =>
                {
                    b.Property<int>("PopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ethos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Hapiness")
                        .HasColumnType("real");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Planet")
                        .HasColumnType("int");

                    b.Property<int?>("PlanetId")
                        .HasColumnType("int");

                    b.Property<int>("PopGameId")
                        .HasColumnType("int");

                    b.Property<float>("Power")
                        .HasColumnType("real");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<string>("Strata")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PopId");

                    b.HasIndex("PlanetId");

                    b.ToTable("Pops");
                });

            modelBuilder.Entity("StellarisSaveParser.Building", b =>
                {
                    b.HasOne("StellarisSaveParser.Planet", null)
                        .WithMany("Buildings")
                        .HasForeignKey("PlanetId");
                });

            modelBuilder.Entity("StellarisSaveParser.Context.Models.District", b =>
                {
                    b.HasOne("StellarisSaveParser.Planet", null)
                        .WithMany("Districts")
                        .HasForeignKey("PlanetId");
                });

            modelBuilder.Entity("StellarisSaveParser.Context.Models.Hyperlane", b =>
                {
                    b.HasOne("StellarisSaveParser.GalacticObject", null)
                        .WithMany("Hyperlanes")
                        .HasForeignKey("GalacticObjectID");
                });

            modelBuilder.Entity("StellarisSaveParser.Planet", b =>
                {
                    b.HasOne("StellarisSaveParser.GalacticObject", null)
                        .WithMany("Planets")
                        .HasForeignKey("GalacticObjectID");
                });

            modelBuilder.Entity("StellarisSaveParser.Pop", b =>
                {
                    b.HasOne("StellarisSaveParser.Planet", null)
                        .WithMany("Pops")
                        .HasForeignKey("PlanetId");
                });
#pragma warning restore 612, 618
        }
    }
}
